import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Innonsh Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="../../public/favicon-SVG.svg" />
      </Head>
      <body
        className={` ${montserrat.variable} antialiased overflow-y-auto scrollbar-thin scrollbar-thumb-[#8B5CF6] scrollbar-track-transparent`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
